### ISSUE TITLE
Ports are hardcoded - Self-Host with different ports is not working

### ISSUE THREAD

**Issue by mrbarletta** [tableflowhq/tableflow#190]
Followed the instructions to test with the docker, but even when setting the ENV file correctly, ports where not working.

So far I found the port 3003 hardcoded here:
[https://github.com/tableflowhq/tableflow/blob/83ba1a5843a59fa41793d67b26183d6b1530c613/admin-ui/src/api/api.ts#L42C48-L42C52](https://github.com/tableflowhq/tableflow/blob/83ba1a5843a59fa41793d67b26183d6b1530c613/admin-ui/src/api/api.ts#L42C48-L42C52)

Then the `docker-compose.base.yml` had also the port 3003 hardcoded, for example, in this case I had to change to 3004 the PORTS definition and the `healthcheck` + the `.env ` variable `TABLEFLOW_API_SERVER_PORT=3004` 
```
  backend:
    platform: linux/amd64
    ports:
      - "3004:3004"
    networks:
      - app_network
    env_file:
      - .env
    volumes:
      - ${PWD}/../.env:/.env
      - tmp:/tmp/tableflow-files
    stop_signal: SIGTERM
    stop_grace_period: 30s
    restart: on-failure
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3004 && echo -e "GET /public/health HTTP/1.1\r\nhost: 127.0.0.1:3004\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "ok"'

```

Even then I can't make it work but seems the env are not being used thoroughly.

it looks so cool I wanted to test it !
